services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_db
    environment:
      POSTGRES_DB: library
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5431:5431'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  library:
    build:
      context: ./
    container_name: library
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data: